#nullable enable

namespace Rectloom.Core
{
    /// <summary>
    /// Identifies the compiler that produced a piece of output.
    /// </summary>
    /// <remarks>
    /// Recorded in metadata so that an update compile can tell whether the output it is about to
    /// touch was generated by a version it still understands.
    /// </remarks>
    public static class RectloomVersion
    {
        /// <summary>Version of the compiler, matching the package version.</summary>
        public const string Current = "0.1.3";
    }
}
